version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
#    volumes:
#      - .:/RPI_Bot
#      - ./migrations:/RPI_Bot/migrations
    working_dir: /api_bot_lab1
    command: >
      sh -c "python main.py"
    environment:
      - TZ=Europe/Moscow
      - db_url=postgresql://USERNAME:PASSWORD@database:5432/DBNAME
    depends_on:
      - database


  database:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=DBNAME
      - POSTGRES_USER=USERNAME
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: