"""change remind2

Revision ID: 0c828fd3fdd6
Revises: c8253179f64f
Create Date: 2024-04-04 16:25:46.616300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c828fd3fdd6'
down_revision: Union[str, None] = 'c8253179f64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remind', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind', sa.Column('image_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
