"""add remind is_at_time

Revision ID: 280fdd655da4
Revises: 7607d9898825
Create Date: 2024-04-13 01:58:54.625429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280fdd655da4'
down_revision: Union[str, None] = '7607d9898825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind', sa.Column('is_at_time', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remind', 'is_at_time')
    # ### end Alembic commands ###
