"""edit remind add name

Revision ID: 311a7b27e7cb
Revises: 8799410969f8
Create Date: 2024-03-01 16:00:47.650654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311a7b27e7cb'
down_revision: Union[str, None] = '8799410969f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remind', 'name')
    # ### end Alembic commands ###
