"""add user_id

Revision ID: 685be8fa4e99
Revises: f2a5c5f37f6f
Create Date: 2024-02-22 14:07:03.281049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685be8fa4e99'
down_revision: Union[str, None] = 'f2a5c5f37f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
