"""edit Category

Revision ID: 6f76a0f4ebd7
Revises: 11a5ca5e4a89
Create Date: 2024-03-01 18:50:19.917514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f76a0f4ebd7'
down_revision: Union[str, None] = '11a5ca5e4a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_name', sa.String(length=100), nullable=True))
    op.drop_column('category', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('category', 'category_name')
    # ### end Alembic commands ###
