"""add remind oneses

Revision ID: 7607d9898825
Revises: d06e01a98379
Create Date: 2024-04-05 21:03:44.838297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7607d9898825'
down_revision: Union[str, None] = 'd06e01a98379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind', sa.Column('ones_month', sa.Integer(), nullable=True))
    op.add_column('remind', sa.Column('ones_years', sa.Integer(), nullable=True))
    op.add_column('remind', sa.Column('date_last_notificate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remind', 'date_last_notificate')
    op.drop_column('remind', 'ones_years')
    op.drop_column('remind', 'ones_month')
    # ### end Alembic commands ###
