"""refactor remind

Revision ID: 859762b9aca3
Revises: 311475ec6a88
Create Date: 2024-03-01 15:35:55.548134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859762b9aca3'
down_revision: Union[str, None] = '311475ec6a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remind_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['remind_id'], ['remind.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remind_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['remind_id'], ['remind.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('remind', sa.Column('type', sa.Integer(), nullable=True))
    op.drop_column('remind', 'category')
    op.drop_column('remind', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind', sa.Column('file_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('remind', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('remind', 'type')
    op.drop_table('file')
    op.drop_table('category')
    # ### end Alembic commands ###
