"""delete is_at_time

Revision ID: bdb93fe03bff
Revises: 280fdd655da4
Create Date: 2024-05-12 19:40:06.168366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb93fe03bff'
down_revision: Union[str, None] = '280fdd655da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remind', 'is_at_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind', sa.Column('is_at_time', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
