"""change remind

Revision ID: c8253179f64f
Revises: aad37a81188f
Create Date: 2024-04-04 16:24:19.798573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8253179f64f'
down_revision: Union[str, None] = 'aad37a81188f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remind', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
