"""Reformat Remind, by adding data_is_deleted

Revision ID: fd3ce125933d
Revises: 6f76a0f4ebd7
Create Date: 2024-03-22 17:49:28.605931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3ce125933d'
down_revision: Union[str, None] = '6f76a0f4ebd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind', sa.Column('date_is_delete', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remind', 'date_is_delete')
    # ### end Alembic commands ###
